import { Plant, HardeningEvent } from './types';

const mockPlants: Plant[] = [
  {
    id: '1',
    code: 'ARM',
    name: 'AR Mini',
    scientificName: 'Alternanthera reineckii \'mini\'',
    description: 'A popular, colorful foreground plant that provides a vibrant red contrast to green aquatic plants.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
      { id: 's1', date: '2024-07-15', explantCount: 30, media: 'MS Media' },
      { id: 's2', date: '2024-06-15', explantCount: 25, media: 'MS Media' },
    ],
  },
  {
    id: '2',
    code: 'ARR',
    name: 'AR Rosanervig',
    scientificName: 'Alternanthera reineckii Rosanervig',
    description: 'Known for its striking pink leaves with light-colored nerves, making it a standout in any aquascape.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
        { id: 's3', date: '2024-07-20', explantCount: 40, media: 'MS Media' },
    ],
  },
  {
    id: '3',
    code: 'Cax',
    name: 'Axelrod\'s Water Trumpet',
    scientificName: 'Cryptocoryne axelrodi',
    description: 'A hardy and adaptable plant with narrow, ruffled leaves, suitable for a variety of water conditions.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '4',
    code: 'CB',
    name: 'Beckett\'s Water Trumpet',
    scientificName: 'Cryptocoryne beckettii',
    description: 'A classic aquarium plant with beautiful, dark bronze-colored leaves that is easy to care for.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
        { id: 's4', date: '2024-07-18', explantCount: 50, media: 'B5 Media' },
    ],
  },
  {
    id: '5',
    code: 'Da',
    name: 'Lance-leaved Sundew',
    scientificName: 'Drosera adele',
    description: 'A carnivorous plant from Australia, also known as the lance-leaved sundew, with long, elegant leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
         { id: 's5', date: '2024-07-22', explantCount: 20, media: 'Peat-based Media' },
    ],
  },
   {
    id: '6',
    code: 'Ds',
    name: 'Spoon-leaved Sundew',
    scientificName: 'Drosera spatulata',
    description: 'A variable, rosette-forming sundew with spoon-shaped leaves, commonly found in Southeast Asia and Australia.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '7',
    code: 'CL',
    name: 'Slender Water Trumpet',
    scientificName: 'Cryptocoryne lucens',
    description: 'A small, slender-leaved Cryptocoryne that is great for foreground or midground placement in an aquarium.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '8',
    code: 'CN',
    name: 'Nur\'s Water Trumpet',
    scientificName: 'Cryptocoryne nurii',
    description: 'A beautiful and sought-after Cryptocoryne known for its patterned leaves with reddish-brown tones.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '9',
    code: 'CSJ',
    name: 'Jwala Spiral Water Trumpet',
    scientificName: 'Cryptocoryne spiralis \'Jwala\'',
    description: 'A unique variety of Cryptocoryne spiralis with long, twisted leaves, creating a dynamic visual effect.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '10',
    code: 'CWP',
    name: 'Pink Wendt\'s Water Trumpet',
    scientificName: 'Cryptocoryne wendtii \'Pink\'',
    description: 'A colorful variant of the popular Cryptocoryne wendtii, showcasing vibrant pink and bronze hues under good lighting.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '11',
    code: 'CWS',
    name: 'Sindoor Wendt\'s Water Trumpet',
    scientificName: 'Cryptocoryne wendtii \'Sindoor\'',
    description: 'A newer variant with intense reddish-brown coloration, named after the traditional vermilion color.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '12',
    code: 'CWG',
    name: 'Green Wendt\'s Water Trumpet',
    scientificName: 'Cryptocoryne wendtii Green',
    description: 'The classic green variant of Cryptocoryne wendtii, a hardy and versatile plant suitable for beginners.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '13',
    code: 'EP',
    name: 'Dwarf Hairgrass',
    scientificName: 'Eleocharis parvula',
    description: 'A popular carpeting plant that creates a lush, green lawn effect in the foreground of an aquarium.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '14',
    code: 'EV',
    name: 'Tall Hairgrass',
    scientificName: 'Eleocharis vivipara',
    description: 'A tall, grass-like plant that adds a unique vertical element to the background of an aquascape.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '15',
    code: 'HCC',
    name: 'Dwarf Baby Tears',
    scientificName: 'Hemianthus callitrichoides \'Cuba\'',
    description: 'One of the smallest aquarium plants in the world, it creates a dense and vibrant green carpet.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '16',
    code: 'HP UK',
    name: 'UK Pinnatifida',
    scientificName: 'Hygrophila pinnatifida \'UK\'',
    description: 'A unique stem plant with pinnately-lobed leaves that can develop a reddish-brown color under intense light.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '17',
    code: 'LB',
    name: 'Brazilian Micro Sword',
    scientificName: 'Lilaeopsis brasiliensis',
    description: 'A low-growing, grass-like carpeting plant that spreads through runners to form a dense lawn.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '18',
    code: 'LAD',
    name: 'Dwarf Ambulia',
    scientificName: 'Limnophila aquatica \'Dwarf\'',
    description: 'A compact variety of Limnophila aquatica, featuring fine, light green leaves in a dense bush.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '19',
    code: 'LAM',
    name: 'Mini Aromatic Rotala',
    scientificName: 'Limnophila aromatica \'Mini\'',
    description: 'A smaller version of the aromatic stem plant, which can develop intense red and orange colors.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '20',
    code: 'LC',
    name: 'Cardinal Plant',
    scientificName: 'Lobelia cardinalis',
    description: 'A versatile plant with vibrant green leaves that can be grown both emersed and submersed.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '21',
    code: 'LR',
    name: 'Creeping Ludwigia',
    scientificName: 'Ludwigia repens',
    description: 'A popular, fast-growing stem plant with leaves that vary from green to deep red depending on light intensity.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '22',
    code: 'MMC',
    name: 'Monte Carlo',
    scientificName: 'Micranthemum \'Monte Carlo\'',
    description: 'A bright green carpeting plant with small, round leaves, excellent for creating a lush foreground.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '23',
    code: 'MMM',
    name: 'Merrill\'s Small-Fruited Plant',
    scientificName: 'Microcarpea minima merrill',
    description: 'A very small, delicate carpeting plant that requires good lighting and CO2 to thrive.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '24',
    code: 'MM',
    name: 'Red-stemmed Myrio',
    scientificName: 'Myriophyllum mattogrossense',
    description: 'A fast-growing stem plant with feathery, light green leaves, providing a fine-textured background.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '25',
    code: 'PE',
    name: 'Erect Pogostemon',
    scientificName: 'Pogostemon erectus',
    description: 'A beautiful stem plant with needle-like, bright green leaves that form a dense, upright bush.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '26',
    code: 'PS',
    name: 'Starry Pogostemon',
    scientificName: 'Pogostemon stellata',
    description: 'A demanding but rewarding plant with star-shaped leaf whorls that can display colors from green to pink and purple.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '27',
    code: 'PP',
    name: 'Mermaid Weed',
    scientificName: 'Proserpinaca palustris',
    description: 'Known as Mermaid Weed, this plant has unique serrated leaves that turn a stunning orange-red under high light.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '28',
    code: 'RI',
    name: 'River Buttercup',
    scientificName: 'Ranunculus inundatus',
    description: 'An interesting foreground plant with unique, deeply lobed leaves that resemble small umbrellas.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '29',
    code: 'RMC',
    name: 'Compact Rotala',
    scientificName: 'Rotala macranda \'Compacta\'',
    description: 'A compact, bushy variant of Rotala macranda with vibrant red and orange leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '30',
    code: 'RMMB',
    name: 'Mini Butterfly Rotala',
    scientificName: 'Rotala macranda \'Mini Butterfly\'',
    description: 'A smaller, delicate Rotala with narrow leaves that can show intense red coloration.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '31',
    code: 'RMMG',
    name: 'Mini Gold Rotala',
    scientificName: 'Rotala macranda Mini Gold',
    description: 'A beautiful variant with golden and pinkish hues, smaller in size than other Rotala macrandra types.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '32',
    code: 'RRA',
    name: 'Assam Rotala',
    scientificName: 'Rotala rotundifolia \'Assam\'',
    description: 'A fast-growing Rotala variant from the Assam region, known for its bright green to reddish leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '33',
    code: 'RRBR',
    name: 'Blood Red Rotala',
    scientificName: 'Rotala rotundifolia \'Blood Red\'',
    description: 'An intensely red variant of Rotala rotundifolia that maintains its color even in moderate light.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '34',
    code: 'RRG',
    name: 'Green Rotala',
    scientificName: 'Rotala rotundifolia \'Green\'',
    description: 'A popular and easy-to-grow stem plant with bright green leaves, perfect for adding a lush background to aquascapes.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '35',
    code: 'HRA',
    name: 'HRA Rotala',
    scientificName: 'Rotala rotundifolia HRA',
    description: 'A striking Rotala variety that develops intense orange to red colors under high light, adding a vibrant splash to the aquarium.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '36',
    code: 'RRB',
    name: 'Bangladesh Rotala',
    scientificName: 'Rotala sp Bangladesh',
    description: 'A fine-leaved stem plant that grows in dense clusters, creating a beautiful, soft texture in the midground or background.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '37',
    code: 'RC',
    name: 'Ceylon Rotala',
    scientificName: 'Rotala sp \'Ceylon\'',
    description: 'A less common Rotala species with delicate, narrow leaves that can range from light green to pinkish hues.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '38',
    code: 'SP',
    name: 'Porto Velho Staurogyne',
    scientificName: 'Staurogyne portovella',
    description: 'A hardy, low-growing plant from Porto Velho, Brazil, that can form a dense, green carpet in the foreground.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '39',
    code: 'SR',
    name: 'Creeping Staurogyne',
    scientificName: 'Staurogyne repens',
    description: 'A fresh green, compact, and hardy plant for the foreground of the aquarium and it is easy to care for.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '40',
    code: 'TPF',
    name: 'Flame Moss',
    scientificName: 'Taxiphyllum \'Flame\'',
    description: 'A unique moss that grows in an upward, flame-like pattern, creating a dense, green fire effect.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '41',
    code: 'TF',
    name: 'River Tonina',
    scientificName: 'Tonina fluviatilis',
    description: 'A challenging but beautiful plant with star-like crowns and light green leaves, often used as a focal point.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '42',
    code: 'UG',
    name: 'Grass-leaved Bladderwort',
    scientificName: 'Utricularia graminifolia',
    description: 'A carnivorous carpeting plant that forms a dense, bright green lawn. It can be challenging to establish but is stunning once settled.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '43',
    code: 'HMW',
    name: 'White Hemianthus',
    scientificName: 'Hemianthus micranthemoides \'White\'',
    description: 'A rare and beautiful variant with white or very light green leaves, requiring high light and CO2.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '44',
    code: 'HTR',
    name: 'Mini Japan Hydrocotyle',
    scientificName: 'Hydrocotyle tripartita \'Mini Japan\'',
    description: 'A fast-growing carpeting plant with small, clover-like leaves. It can create a dense, low-maintenance carpet.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '45',
    code: 'BP',
    name: 'Bucephalandra Sp.',
    scientificName: 'Bucephalandra Sp.',
    description: 'A general entry for various species of Bucephalandra, slow-growing rhizome plants with iridescent leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '46',
    code: 'BPW',
    name: 'Bucephalandra White',
    scientificName: 'Bucephalandra \'White\'',
    description: 'A rare and sought-after Bucephalandra variety with predominantly white or light-colored leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  }
];


const mockHardeningData: HardeningEvent[] = [
    {
        id: 'h1',
        plantId: '1',
        plantName: 'Alternanthera reineckii \'mini\'',
        dateTransferred: '2024-05-15',
        transferredCount: 50,
        stage: 'growing',
        acclimatizationSuccessRate: 0.9,
        dateMovedToGrowth: '2024-06-01',
        growthSuccessRate: 0.95,
        notes: 'Vigorous growth in the greenhouse.'
    },
    {
        id: 'h2',
        plantId: '3',
        plantName: 'Cryptocoryne axelrodi',
        dateTransferred: '2024-06-01',
        transferredCount: 30,
        stage: 'acclimatizing',
        notes: 'Initial transfer to a controlled environment chamber.'
    },
    {
        id: 'h3',
        plantId: '1',
        plantName: 'Alternanthera reineckii \'mini\'',
        dateTransferred: '2024-04-20',
        transferredCount: 25,
        stage: 'exported',
        acclimatizationSuccessRate: 0.88,
        dateMovedToGrowth: '2024-05-10',
        growthSuccessRate: 0.92,
        dateExported: '2024-06-05',
        exportedTo: 'GreenLeaf Nursery',
        notes: 'Batch sold to a commercial partner.'
    },
    {
        id: 'h4',
        plantId: '2',
        plantName: 'Alternanthera reineckii Rosanervig',
        dateTransferred: '2024-06-10',
        transferredCount: 100,
        stage: 'acclimatizing',
        notes: 'Large batch, monitoring closely for mold.'
    }
];


export const getPlants = (): Plant[] => {
  return mockPlants;
}

export const getPlantById = (id: string): Plant | undefined => {
  return mockPlants.find((plant) => plant.id === id);
}

export const getHardeningData = (): HardeningEvent[] => {
    return mockHardeningData;
}
