
import { Plant, HardeningEvent } from './types';

const mockPlants: Plant[] = [
  {
    id: '1',
    name: 'Alternanthera reineckii \'mini\'',
    scientificName: 'Alternanthera reineckii \'mini\'',
    description: 'A popular, colorful foreground plant that provides a vibrant red contrast to green aquatic plants.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
      { id: 's1', date: '2024-07-15', explantCount: 30, media: 'MS Media' },
      { id: 's2', date: '2024-06-15', explantCount: 25, media: 'MS Media' },
    ],
  },
  {
    id: '2',
    name: 'Alternanthera reineckii Rosanervig',
    scientificName: 'Alternanthera reineckii Rosanervig',
    description: 'Known for its striking pink leaves with light-colored nerves, making it a standout in any aquascape.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
        { id: 's3', date: '2024-07-20', explantCount: 40, media: 'MS Media' },
    ],
  },
  {
    id: '3',
    name: 'Cryptocoryne axelrodi',
    scientificName: 'Cryptocoryne axelrodi',
    description: 'A hardy and adaptable plant with narrow, ruffled leaves, suitable for a variety of water conditions.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '4',
    name: 'Cryptocoryne beckettii',
    scientificName: 'Cryptocoryne beckettii',
    description: 'A classic aquarium plant with beautiful, dark bronze-colored leaves that is easy to care for.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
        { id: 's4', date: '2024-07-18', explantCount: 50, media: 'B5 Media' },
    ],
  },
  {
    id: '5',
    name: 'Drosera adele',
    scientificName: 'Drosera adele',
    description: 'A carnivorous plant from Australia, also known as the lance-leaved sundew, with long, elegant leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [
         { id: 's5', date: '2024-07-22', explantCount: 20, media: 'Peat-based Media' },
    ],
  },
   {
    id: '6',
    name: 'Drosera spatulata',
    scientificName: 'Drosera spatulata',
    description: 'A variable, rosette-forming sundew with spoon-shaped leaves, commonly found in Southeast Asia and Australia.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '7',
    name: 'Cryptocoryne lucens',
    scientificName: 'Cryptocoryne lucens',
    description: 'A small, slender-leaved Cryptocoryne that is great for foreground or midground placement in an aquarium.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '8',
    name: 'Cryptocoryne nurii',
    scientificName: 'Cryptocoryne nurii',
    description: 'A beautiful and sought-after Cryptocoryne known for its patterned leaves with reddish-brown tones.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '9',
    name: 'Cryptocoryne spiralis \'Jwala\'',
    scientificName: 'Cryptocoryne spiralis \'Jwala\'',
    description: 'A unique variety of Cryptocoryne spiralis with long, twisted leaves, creating a dynamic visual effect.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '10',
    name: 'Cryptocoryne wendtii \'Pink\'',
    scientificName: 'Cryptocoryne wendtii \'Pink\'',
    description: 'A colorful variant of the popular Cryptocoryne wendtii, showcasing vibrant pink and bronze hues under good lighting.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '11',
    name: 'Cryptocoryne wendtii \'Sindoor\'',
    scientificName: 'Cryptocoryne wendtii \'Sindoor\'',
    description: 'A newer variant with intense reddish-brown coloration, named after the traditional vermilion color.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '12',
    name: 'Cryptocoryne wendtii Green',
    scientificName: 'Cryptocoryne wendtii Green',
    description: 'The classic green variant of Cryptocoryne wendtii, a hardy and versatile plant suitable for beginners.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '13',
    name: 'Anubias barteri var. nana',
    scientificName: 'Anubias barteri var. nana',
    description: 'A small, attractive plant with broad, deep green leaves. It is very hardy and can thrive in a variety of conditions.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '14',
    name: 'Anubias \'Petite\'',
    scientificName: 'Anubias barteri var. nana \'Petite\'',
    description: 'A miniature version of Anubias barteri var. nana, perfect for nano tanks or as a foreground accent.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '15',
    name: 'Bucephalandra \'Wavy Green\'',
    scientificName: 'Bucephalandra \'Wavy Green\'',
    description: 'A popular Bucephalandra variety with wavy, green leaves that can develop a bluish tint under optimal lighting.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '16',
    name: 'Bucephalandra \'Kedagang\'',
    scientificName: 'Bucephalandra \'Kedagang\'',
    description: 'Known for its narrow, dark leaves that can have an iridescent sheen. It is a slow-growing but beautiful plant.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '17',
    name: 'Bucephalandra \'Brownie Ghost\'',
    scientificName: 'Bucephalandra \'Brownie Ghost\'',
    description: 'A highly sought-after Bucephalandra with deep, brownish-purple leaves that can appear almost ghostly.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '18',
    name: 'Bucephalandra \'Lamandau Mini Red\'',
    scientificName: 'Bucephalandra \'Lamandau Mini Red\'',
    description: 'A small Bucephalandra with reddish leaves, ideal for adding a splash of color to small aquascapes.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '19',
    name: 'Cryptocoryne wendtii \'Green Gecko\'',
    scientificName: 'Cryptocoryne wendtii \'Green Gecko\'',
    description: 'A variety of Cryptocoryne wendtii with bright green, slightly ruffled leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '20',
    name: 'Cryptocoryne wendtii \'Mi Oya\'',
    scientificName: 'Cryptocoryne wendtii \'Mi Oya\'',
    description: 'A classic variety of Cryptocoryne from Sri Lanka, with reddish-brown leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '21',
    name: 'Cryptocoryne wendtii \'Brown\'',
    scientificName: 'Cryptocoryne wendtii \'Brown\'',
    description: 'A popular and easy-to-grow Cryptocoryne with rich, brown-colored leaves.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '22',
    name: 'Cryptocoryne parva',
    scientificName: 'Cryptocoryne parva',
    description: 'The smallest of the Cryptocoryne species, making it an excellent choice for a foreground carpet.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '23',
    name: 'Cryptocoryne spiralis \'Tiger\'',
    scientificName: 'Cryptocoryne spiralis \'Tiger\'',
    description: 'A striking Cryptocoryne with long, narrow leaves that feature a distinctive tiger-stripe pattern.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '24',
    name: 'Eleocharis parvula',
    scientificName: 'Eleocharis parvula',
    description: 'Also known as Dwarf Hairgrass, this plant creates a lush, green carpet effect in the foreground of an aquarium.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '25',
    name: 'Eleocharis vivipara',
    scientificName: 'Eleocharis vivipara',
    description: 'A tall, grass-like plant that can form dense thickets, creating a jungle-like background in larger tanks.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '26',
    name: 'Hemianthus callitrichoides \'Cuba\'',
    scientificName: 'Hemianthus callitrichoides \'Cuba\'',
    description: 'One of the smallest aquarium plants in the world, it forms a dense, bright green carpet over the substrate.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '27',
    name: 'Hemianthus micranthemoides \'White\'',
    scientificName: 'Hemianthus micranthemoides \'White\'',
    description: 'A rare and beautiful variant with white or very light green leaves, requires high light and CO2.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '28',
    name: 'Hydrocotyle tripartita Mini',
    scientificName: 'Hydrocotyle tripartita Mini',
    description: 'A fast-growing, clover-like plant that can be used as a carpeting plant or a trailing background plant.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
  {
    id: '29',
    name: 'Hygrophila pinnatifida \'UK\'',
    scientificName: 'Hygrophila pinnatifida \'UK\'',
    description: 'A unique stem plant with pinnately-lobed leaves that can develop a reddish-brown color under intense light.',
    photoUrl: 'https://placehold.co/600x400.png',
    type: 'tc',
    subcultureHistory: [],
  },
];


const mockHardeningData: HardeningEvent[] = [
    {
        id: 'h1',
        plantId: '1',
        plantName: 'Alternanthera reineckii \'mini\'',
        dateTransferred: '2024-05-15',
        transferredCount: 50,
        stage: 'growing',
        acclimatizationSuccessRate: 0.9,
        dateMovedToGrowth: '2024-06-01',
        growthSuccessRate: 0.95,
        notes: 'Vigorous growth in the greenhouse.'
    },
    {
        id: 'h2',
        plantId: '3',
        plantName: 'Cryptocoryne axelrodi',
        dateTransferred: '2024-06-01',
        transferredCount: 30,
        stage: 'acclimatizing',
        notes: 'Initial transfer to a controlled environment chamber.'
    },
    {
        id: 'h3',
        plantId: '1',
        plantName: 'Alternanthera reineckii \'mini\'',
        dateTransferred: '2024-04-20',
        transferredCount: 25,
        stage: 'exported',
        acclimatizationSuccessRate: 0.88,
        dateMovedToGrowth: '2024-05-10',
        growthSuccessRate: 0.92,
        dateExported: '2024-06-05',
        exportedTo: 'GreenLeaf Nursery',
        notes: 'Batch sold to a commercial partner.'
    },
    {
        id: 'h4',
        plantId: '2',
        plantName: 'Alternanthera reineckii Rosanervig',
        dateTransferred: '2024-06-10',
        transferredCount: 100,
        stage: 'acclimatizing',
        notes: 'Large batch, monitoring closely for mold.'
    }
];


export const getPlants = (): Plant[] => {
  return mockPlants;
}

export const getPlantById = (id: string): Plant | undefined => {
  return mockPlants.find((plant) => plant.id === id);
}

export const getHardeningData = (): HardeningEvent[] => {
    return mockHardeningData;
}
